language: generic
notifications:
  email:
    on_success: never
    on_failure: always
before_script:
  - if [ -a .git/shallow ]; then git fetch --unshallow; fi
  - git checkout master
script:
  - ./update.sh
