# This file is released into the public domain
name: Update
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo wget -O $(git --exec-path)/git-filter-repo \
            https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo
          sudo chmod +x $(git --exec-path)/git-filter-repo
      - uses: actions/checkout@v3
        with:
          repository: llvm/llvm-project
          ref: main
          fetch-depth: 0
      - run: git filter-repo --subdirectory-filter llvm/utils/vim
      - run: git remote add origin https://github.com/ararslan/llvm.vim.git
      - uses: ad-m/github-push-action@master
        with:
          branch: main
